#if !canImport(ObjectiveC)
import XCTest

extension DDSwiftTracerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DDSwiftTracerTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DDSwiftTracerTests.__allTests__DDSwiftTracerTests),
    ]
}
#endif
